2019-04-07 21:19:32,124 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 2 hosts
2019-04-07 21:19:41,357 - nornir.core.task -    ERROR -      start() - Host 'XRV': task 'napalm_get' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/napalm/iosxr/iosxr.py", line 80, in open
    self.device.open()
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/pyIOSXR/iosxr.py", line 175, in open
    self._enter_xml_mode()
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/pyIOSXR/iosxr.py", line 233, in _enter_xml_mode
    raise ConnectError('XML agent is not enabled. Please configure `xml agent tty iteration off`!', self)
pyIOSXR.exceptions.ConnectError: XML agent is not enabled. Please configure `xml agent tty iteration off`!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_get.py", line 49, in napalm_get
    device = task.host.get_connection("napalm", task.nornir.config)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/inventory.py", line 302, in get_connection
    extras=conn.extras,
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/inventory.py", line 352, in open_connection
    configuration=configuration,
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/connections/napalm.py", line 51, in open
    connection.open()
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/napalm/iosxr/iosxr.py", line 82, in open
    raise ConnectionException(conn_err.args[0])
napalm.base.exceptions.ConnectionException: XML agent is not enabled. Please configure `xml agent tty iteration off`!

2019-04-07 21:21:12,040 -  nornir.core -     INFO -        run() - Running task 'napalm_get' with args {'getters': ['get_facts']} on 2 hosts
2019-04-07 22:04:51,043 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:05:08,533 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:05:26,002 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:07:58,177 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:07:58,181 - nornir.core.task -    ERROR -      start() - Host 'CSR': task 'run_commands' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "script.py", line 21, in run_commands
    cmds_only = [cmd['command'] for cmd in commands]
NameError: name 'commands' is not defined

2019-04-07 22:07:58,181 - nornir.core.task -    ERROR -      start() - Host 'XRV': task 'run_commands' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "script.py", line 21, in run_commands
    cmds_only = [cmd['command'] for cmd in commands]
NameError: name 'commands' is not defined

2019-04-07 22:08:38,684 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:08:38,687 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ip ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:08:38,688 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:08:38,750 - nornir.core.task -    ERROR -      start() - Host 'CSR': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:08:38,750 - nornir.core.task -    ERROR -      start() - Host 'XRV': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:09:22,832 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:09:22,836 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ip ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:09:22,836 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:09:22,898 - nornir.core.task -    ERROR -      start() - Host 'CSR': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:09:22,899 - nornir.core.task -    ERROR -      start() - Host 'XRV': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:10:02,379 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:10:02,382 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ip ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:10:02,382 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:10:02,425 - nornir.core.task -    ERROR -      start() - Host 'CSR': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:10:02,425 - nornir.core.task -    ERROR -      start() - Host 'XRV': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:10:32,711 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:10:32,715 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ip ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:10:32,715 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:10:32,778 - nornir.core.task -    ERROR -      start() - Host 'CSR': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:10:32,779 - nornir.core.task -    ERROR -      start() - Host 'XRV': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:11:06,299 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:11:06,302 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ip ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:11:06,303 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:11:06,366 - nornir.core.task -    ERROR -      start() - Host 'CSR': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:11:06,367 - nornir.core.task -    ERROR -      start() - Host 'XRV': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:11:11,643 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:11:11,646 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ip ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:11:11,647 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:11:11,711 - nornir.core.task -    ERROR -      start() - Host 'CSR': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:11:11,711 - nornir.core.task -    ERROR -      start() - Host 'XRV': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:17:07,408 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:17:07,412 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ip ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:17:07,412 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:17:07,476 - nornir.core.task -    ERROR -      start() - Host 'CSR': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:17:07,476 - nornir.core.task -    ERROR -      start() - Host 'XRV': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:18:57,973 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:18:57,981 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ip ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:18:57,982 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:18:58,023 - nornir.core.task -    ERROR -      start() - Host 'CSR': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:18:58,023 - nornir.core.task -    ERROR -      start() - Host 'XRV': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:20:18,779 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:20:18,782 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ip ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:20:18,783 -  nornir.core -     INFO -        run() - Running task 'napalm_cli' with args {'commands': ['show ospf neighbor', 'show version']} on 2 hosts
2019-04-07 22:20:18,846 - nornir.core.task -    ERROR -      start() - Host 'CSR': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:20:18,846 - nornir.core.task -    ERROR -      start() - Host 'XRV': task 'napalm_cli' failed with traceback:
Traceback (most recent call last):
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/core/task.py", line 67, in start
    r = self.task(self, **self.params)
  File "/home/centos/environments/nornir2/lib64/python3.6/site-packages/nornir/plugins/tasks/networking/napalm_cli.py", line 18, in napalm_cli
    result = device.cli(commands)
AttributeError: 'UnestablishedConnection' object has no attribute 'cli'

2019-04-07 22:23:11,795 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:30:24,707 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:34:19,187 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:34:38,125 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:42:55,833 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:45:09,371 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:49:31,081 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:50:05,756 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
2019-04-07 22:51:01,171 -  nornir.core -     INFO -        run() - Running task 'run_commands' with args {} on 2 hosts
